### ISSUE TITLE
More descriptive readme file

### ISSUE THREAD

**Issue by chanjuping** [cycool29/shooting-game#1]
The readme file for the project should have more details about the project. Although it is still in its initial stages. For example, what kind of shooting game is this, what are the controls, or even how to launch it.

**Comment by cycool29** [comment]
Created README in ce732ea1b0f8ba325fe0e9f7c60f9dd77d15fad4  and added `How to play` section in d0739cf0486ab117864ee6a23fe4b748be4878c9 . 😁

**Comment by chanjuping** [comment]
Very nicely done! Good job.
