### ISSUE TITLE
wrong file

### ISSUE THREAD

**Issue by gl91306** [cycool29/shooting-game#2]
Great game, but in your readme you specified that the file to be executed should be main.py, when it should really be menu.py. Also I recommend that you slow the objects down. Also you need to specify that pygame_menu needs to be installed along with pygame

**Comment by cycool29** [comment]
Thanks, will update the README now.

> Also I recommend that you slow the objects down.

Ya, as I run it in my Raspberry Pi, the object is actually in normal speed for me.
Planning to make a Settings page to adjust them.

**Comment by cycool29** [comment]
Updated README in https://github.com/cycool29/shooting-game/commit/42ca212c755e1baf75fd5e49065d995441974781 and added [Setting page](https://github.com/cycool29/shooting-game/projects/1#card-71350633) to my ideas list!

**Comment by cycool29** [comment]
Added Settings page to adjust COVID's moving speed. Closing.
